name: Static Analysis Tests
on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: Run Bandit Scan
        run: |
          pip install bandit
          bandit -r app.py -f txt -o banditResults.txt || true

      - name: Run Semgrep Scan
        run: |
          pip install semgrep
          semgrep scan --config auto --text -o semgrepResults.txt || true

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: |
            banditResults.txt
            semgrepResults.txt